/* generated by JUL Designer version 1.9.1 */
/* 'JWL Components - Custom element test' namespace */
JUL.ns('JWL.tests.custom');

JUL.apply(JWL.tests.custom,
/* begin 'JWL Components - Custom element test' */
{
	keepBindings: false,
	listenersProperty: 'listeners',
	noLogic: false,
	ns: 'JWL.tests.custom',
	suggestedFramework: 'html',
	title: 'JWL Components - Custom element test',
	version: '1.1484797480549',
	init: function () {
		var oParser = new JWL.Parser(this.parserConfig);
		oParser.create(this.ui, this.logic, document.body);
	}
}
/* end 'JWL Components - Custom element test' */
);

JWL.tests.custom.parserConfig =
/* begin 'JWL Components - Custom element test' parser config */
{
	customFactory: 'JWL.custom',
	defaultClass: 'html',
	topDown: true,
	useTags: true
}
/* end 'JWL Components - Custom element test' parser config */
;

JWL.tests.custom.ui =
/* begin 'JWL Components - Custom element test' UI */
{
	tag: 'div',
	children: [
		{tag: 'frameplayer', id: 'custom-frameplayer', css: 'abc'}
	]
}
/* end 'JWL Components - Custom element test' UI */
;

JWL.tests.custom.logic =
/* begin 'JWL Components - Custom element test' logic */
{
	'custom-frameplayer': {
		'data-image-height': '144', 'data-image-src': 'media/frames/frame05.jpg', 'data-image-width': '256',
		 'data-options': '{"template":"media/frames/frame{n}.jpg","range":[1,30],"zeropad":true,"interval":400}'
	}
}
/* end 'JWL Components - Custom element test' logic */
;

