/* generated by JUL Designer version 1.9.1 */
/* 'JWL Components - Wrapper test' namespace */
JUL.ns('JWL.tests.wrapper');

JUL.apply(JWL.tests.wrapper,
/* begin 'JWL Components - Wrapper test' */
{
	keepBindings: false,
	listenersProperty: 'listeners',
	noLogic: false,
	ns: 'JWL.tests.wrapper',
	suggestedFramework: 'html',
	title: 'JWL Components - Wrapper test',
	version: '1.1484797551900',
	init: function () {
		var oParser = new JWL.Parser(this.parserConfig);
		oParser.create(this.ui, this.logic, document.body);
	}
}
/* end 'JWL Components - Wrapper test' */
);

JWL.tests.wrapper.parserConfig =
/* begin 'JWL Components - Wrapper test' parser config */
{
	customFactory: 'JWL.factory',
	defaultClass: 'html',
	topDown: true,
	useTags: true
}
/* end 'JWL Components - Wrapper test' parser config */
;

JWL.tests.wrapper.ui =
/* begin 'JWL Components - Wrapper test' UI */
{
	tag: 'div',
	children: [
		{tag: 'frameplayer', id: 'class-frameplayer', css: 'abc'}
	]
}
/* end 'JWL Components - Wrapper test' UI */
;

JWL.tests.wrapper.logic =
/* begin 'JWL Components - Wrapper test' logic */
{
	'class-frameplayer': {
		'data-image-height': '144', 'data-image-src': 'media/frames/frame05.jpg', 'data-image-width': '256',
		 'data-options': '{"template":"media/frames/frame{n}.jpg","range":[1,30],"zeropad":true,"interval":400}'
	}
}
/* end 'JWL Components - Wrapper test' logic */
;

