/* generated by JUL Designer version 1.9.1 */
/* 'JWL Components - SVG Logo' namespace */
JUL.ns('JWL.resources.svglogo');

JUL.apply(JWL.resources.svglogo,
/* begin 'JWL Components - SVG Logo' */
{
	keepBindings: false,
	listenersProperty: 'listeners',
	noLogic: true,
	ns: 'JWL.resources.svglogo',
	suggestedFramework: 'html',
	title: 'JWL Components - SVG Logo',
	version: '1.1484797448211',
	init: function () {
		var oParser = new JUL.UI.Parser(this.parserConfig);
		oParser.create(this.ui, this.logic, document.body);
	}
}
/* end 'JWL Components - SVG Logo' */
);

JWL.resources.svglogo.parserConfig =
/* begin 'JWL Components - SVG Logo' parser config */
{
	customFactory: 'JUL.UI.createDom',
	defaultClass: 'svg',
	topDown: true,
	useTags: true
}
/* end 'JWL Components - SVG Logo' parser config */
;

JWL.resources.svglogo.ui =
/* begin 'JWL Components - SVG Logo' UI */
{
	tag: 'svg',
	fill: 'transparent',
	height: '300',
	viewBox: '-10 -10 20 20',
	width: '300',
	children: [
		{tag: 'polygon', points: '-2,-1 2,-1 0,-8', stroke: 'yellow'},
		{tag: 'polygon', points: '-2,1 2,1 0,8', stroke: 'blue'},
		{tag: 'polygon', points: '-1,-2 -1,2 -8,0', stroke: 'red'},
		{tag: 'polygon', points: '1,-2 1,2 8,0', stroke: 'lightgreen'}
	]
}
/* end 'JWL Components - SVG Logo' UI */
;

JWL.resources.svglogo.logic =
/* begin 'JWL Components - SVG Logo' logic */
null
/* end 'JWL Components - SVG Logo' logic */
;

